---
title: "Learn Object-Oriented Programming"
type: "challenge"
description: "A set of tests that will guide you through the basics of Object-Oriented Programming."
visibility: "onsite"
tags: "oop, ignition"
ignore:
- "learn-oop.md"
